### PR TITLE
Map client

### PR DESCRIPTION
**Pull request by pavittr**
This change is [Reviewable](https://reviewable.io/reviews/gameontext/gameon-room-java/26)

### CODE REVIEW

**Comment by ebullient** [comment]
Reviewed 12 of 13 files at r1.
Review status: 12 of 13 files reviewed at latest revision, 13 unresolved discussions.

---

*[gojava-application/src/main/java/application/Application.java, line 164 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtB4ykTzJbIb4Jc5ow:-KTtB4yoVUxSQGZw5zcP:bddkodn) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/application/Application.java#L164)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>             RoomInfo roomInfo = getRoomInfo();
>             if (roomInfo != null) {
>             	response.add(NAME, roomInfo.getName());
>             	String description = roomInfo.getDescription();
>             	response.add(DESCRIPTION, (description == null) ? "A badly described room" : description);
</details>

Make RoomInfo a member variable, to make it easier for the room description to be reused/updated/forwarded between addNewPlayer and processCommand (below)

getRoomInfo should make sure that it always returns an object..

---

*[gojava-application/src/main/java/application/Application.java, line 201 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtBGKVURr086hnXUnK:-KTtBGKVURr086hnXUnL:b-654mwi) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/application/Application.java#L201)):*
> ```Java
>             	response.add(NAME, roomInfo.getName());
>             	String description = roomInfo.getDescription();
>             	response.add(DESCRIPTION, (description == null) ? "A badly described room" : description);
> ```

This is duplicate code for above. Simplify with a reusable RoomInfo object.

Might add as a comment around that RoomInfo object that a room could consider changing its description at runtime over time, or per user, or across instances, or... 

---

*[gojava-application/src/main/java/application/Application.java, line 216 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtBYvY57UD18uOnwa_:-KTtBYv_trtwOLE-Mrpd:b-74biko) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/application/Application.java#L216)):*
> ```Java
>             }
> 
>             if ( exitDirection == null) {
> ```

You do still need to make sure that all exits are defined. They *should* be, but accidents happen.

---

*[gojava-application/src/main/java/map/client/Log.java, line 27 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtBtulAUJ015QUAGGX:-KTtBtulAUJ015QUAGGY:b-nqfl44) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/Log.java#L27)):*
> ```Java
>  */
> public class Log {
>     private final static Logger log = Logger.getLogger("net.wasdev.gameon.mediator");
> ```

Bad package here... 

---

*[gojava-application/src/main/java/map/client/Log.java, line 57 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtC2fh3-nzwZtgbvpM:-KTtC2fh3-nzwZtgbvpN:b-b2wjp2) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/Log.java#L57)):*
> ```Java
>      * @return Original Level or INFO level, whichever is greater
>      */
>     private static Level useLevel(Level level) {
> ```

We might use a variable here to determine whether or not this takes effect. Should be possible to _not_ do this level promotion in some environments.

---

*[gojava-application/src/main/java/map/client/MapClient.java, line 51 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtCGJSox_61eoTWswu:-KTtCGJTzXUtgdSDfkuA:bu1ok15) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/MapClient.java#L51)):*
> ```Java
> public class MapClient {
> 
> 	private static final String mapLocation = "https://game-on.org/map/v1/sites";
> ```

Should still allow this to be injected (and cope if it isn't). We have the possibility on the horizon for additional domains for test/staging... would be nice for the example to handle that.

---

*[gojava-application/src/main/java/map/client/MapResponseReader.java, line 31 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtCz6v0CMpnuSo0NJU:-KTtCz6v0CMpnuSo0NJV:b-mdnanm) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/MapResponseReader.java#L31)):*
> ```Java
> @Provider
> @Consumes(MediaType.APPLICATION_JSON)
> public class MapResponseReader implements MessageBodyReader<Site> {
> ```

We need this because we aren't using Jackson?

---

*[gojava-application/src/main/java/map/client/MapResponseReader.java, line 58 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtCnjQXgVMHSeUrR4r:-KTtCnjRwWSHFwfdyvi9:b-38g0e) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/MapResponseReader.java#L58)):*
> ```Java
> 			site.setType(sanitiseNull(returnedJson.getJsonString("type")));
> 			site.setId(sanitiseNull(returnedJson.getJsonString("_id")));
> ```

Why do we need to sanitize null? (because we aren't using Jackson that automatically ignores null attributes?) (especially given that we are using Jackson w/ annotations below?)

---

*[gojava-application/src/main/java/map/client/model/Doors.java, line 20 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtDJVsqXU0T-1jov85:-KTtDJVsqXU0T-1jov86:b-fhg1ua) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/model/Doors.java#L20)):*
> ```Java
> import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
> 
> @JsonIgnoreProperties(ignoreUnknown = true)
> ```

Also need @JsonInclude(Include.NON_EMPTY) .. though we won't be marshalling these back out in the usual course of things

---

*[gojava-application/src/main/java/map/client/model/Exit.java, line 17 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtDU-c8Vj03Ol73VOd:-KTtDU-dNkQfLnSULpXQ:b-mrlmzc) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/model/Exit.java#L17)):*
> ```Java
>  *******************************************************************************/
> package map.client.model;
> ```

Comments.
Jackson annotations for avoiding empty values and ignoring unknown attributes

---

*[gojava-application/src/main/java/map/client/model/Exits.java, line 22 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtD_PonADZQYvqiwhC:-KTtD_PonADZQYvqiwhD:b-gyq8dm) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/model/Exits.java#L22)):*
> ```Java
> import javax.json.JsonObjectBuilder;
> 
> public class Exits {
> ```

JAckson annotations for ignoring nulls and unknown attributes

---

*[gojava-application/src/main/java/map/client/model/RoomInfo.java, line 18 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtDfvkIuCSJS-_gMRQ:-KTtDfvkIuCSJS-_gMRR:b4nvq4m) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/model/RoomInfo.java#L18)):*
> ```Java
> package map.client.model;
> 
> public class RoomInfo {
> ```

Jackson annotations for ignoring unknown and empty attributes
Should include assigning dummy strings for missing descriptive values 

---

*[gojava-application/src/main/java/map/client/model/Site.java, line 17 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtDlSgNhciB3F5Mp5O:-KTtDlSgNhciB3F5Mp5P:bjvyj59) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/model/Site.java#L17)):*
> ```Java
>  *******************************************************************************/
> package map.client.model;
> ```

Jackson annotations for ignoring unknown/empty attributes. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26)*

**Comment by ebullient** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26)*

**Comment by pavittr** [comment]
Review status: 5 of 20 files reviewed at latest revision, 13 unresolved discussions.

---

*[gojava-application/src/main/java/application/Application.java, line 164 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtB4ykTzJbIb4Jc5ow:-KTxtmUYveblepJ10Bdl:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/application/Application.java#L164)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> >             RoomInfo roomInfo = getRoomInfo();
> >             if (roomInfo != null) {
> >             	response.add(NAME, roomInfo.getName());
> >             	String description = roomInfo.getDescription();
> >             	response.add(DESCRIPTION, (description == null) ? "A badly described room" : description);
> 
> Make RoomInfo a member variable, to make it easier for the room description to be reused/updated/forwarded between addNewPlayer and processCommand (below)
> 
> getRoomInfo should make sure that it always returns an object..
</details>
Done.

---

*[gojava-application/src/main/java/application/Application.java, line 201 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtBGKVURr086hnXUnK:-KTxtoKApQ5J3oM6TCm0:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/application/Application.java#L201)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> This is duplicate code for above. Simplify with a reusable RoomInfo object.
> 
> Might add as a comment around that RoomInfo object that a room could consider changing its description at runtime over time, or per user, or across instances, or... 
</details>
Done.

---

*[gojava-application/src/main/java/application/Application.java, line 216 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtBYvY57UD18uOnwa_:-KTxtp-As_3bDMwyvE-8:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/application/Application.java#L216)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> You do still need to make sure that all exits are defined. They *should* be, but accidents happen.
</details>
Done.

---

*[gojava-application/src/main/java/map/client/Log.java, line 27 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtBtulAUJ015QUAGGX:-KTxtqHaA5-eVzhI8N6B:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/Log.java#L27)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Bad package here... 
</details>
Done.

---

*[gojava-application/src/main/java/map/client/Log.java, line 57 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtC2fh3-nzwZtgbvpM:-KTxtrgj-EzbQp0Erqt8:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/Log.java#L57)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> We might use a variable here to determine whether or not this takes effect. Should be possible to _not_ do this level promotion in some environments.
</details>
Done.

---

*[gojava-application/src/main/java/map/client/MapClient.java, line 51 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtCGJSox_61eoTWswu:-KTxttsoN-ARAwE6inS9:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/MapClient.java#L51)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Should still allow this to be injected (and cope if it isn't). We have the possibility on the horizon for additional domains for test/staging... would be nice for the example to handle that.
</details>
Done.

---

*[gojava-application/src/main/java/map/client/MapResponseReader.java, line 31 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtCz6v0CMpnuSo0NJU:-KTxtwk143vD7Y44co-d:b4825o4) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/MapResponseReader.java#L31)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> We need this because we aren't using Jackson?
</details>
Yes, basically. I was planning on having an example of using JSON-P

---

*[gojava-application/src/main/java/map/client/MapResponseReader.java, line 58 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtCnjQXgVMHSeUrR4r:-KTxuBRXdEZrI1Af23sJ:bvnasw2) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/MapResponseReader.java#L58)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Why do we need to sanitize null? (because we aren't using Jackson that automatically ignores null attributes?) (especially given that we are using Jackson w/ annotations below?)
</details>
Yeah that is part of it.

---

*[gojava-application/src/main/java/map/client/model/Doors.java, line 20 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtDJVsqXU0T-1jov85:-KTxuI_lIjtgZHV2kg0_:b-5rl4nz) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/model/Doors.java#L20)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Also need @JsonInclude(Include.NON_EMPTY) .. though we won't be marshalling these back out in the usual course of things
</details>
Removed so we can focus on JSON-P

---

*[gojava-application/src/main/java/map/client/model/RoomInfo.java, line 18 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtDfvkIuCSJS-_gMRQ:-KTxuPOAIuwhdSUjHy_h:b6nt2f5) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/model/RoomInfo.java#L18)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Jackson annotations for ignoring unknown and empty attributes
> Should include assigning dummy strings for missing descriptive values 
</details>
So not doing this as a result of focusing on JSON-P. For the null attributes, I don;t want to force non-null values at this stage as it might 

---

*[gojava-application/src/main/java/map/client/model/Site.java, line 17 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtDlSgNhciB3F5Mp5O:-KTy8mNqM1OjwTJOk6Gk:b3hss53) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/model/Site.java#L17)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Jackson annotations for ignoring unknown/empty attributes. 
</details>
Handled

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26)*

**Comment by pavittr** [comment]
Review status: 5 of 20 files reviewed at latest revision, 13 unresolved discussions.

---

*[gojava-application/src/main/java/map/client/model/Exit.java, line 17 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtDU-c8Vj03Ol73VOd:-KTy94RGWxw6U4zBsrRl:b3hss53) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/model/Exit.java#L17)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Comments.
> Jackson annotations for avoiding empty values and ignoring unknown attributes
</details>
Handled

---

*[gojava-application/src/main/java/map/client/model/Exits.java, line 22 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26#-KTtD_PonADZQYvqiwhC:-KTy92ijdfsIBLOP9qFn:b3hss53) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cb79395ddb03e0b57d13ea814d1db81aac40a45/gojava-application/src/main/java/map/client/model/Exits.java#L22)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> JAckson annotations for ignoring nulls and unknown attributes
</details>
Handled

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26)*

**Comment by ebullient** [comment]
Reviewed 17 of 17 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/26)*

**Pull request merged**
