### PR TITLE
CDI injection issues, ENV var usage, Travis for PR

### PR DESCRIPTION
**Pull request by ebullient**
add beans.xml
revise constant lookup/declaration for room id to allow for environment variable
publish application into apps dir (not dropins)

change dependencies in pom.xml
create travis build to verify tests for new PRs

---
This change is [Reviewable](https://reviewable.io/reviews/gameontext/gameon-room-java/43)

### CODE REVIEW

**Comment by BarDweller** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/43)*

**Comment by BarDweller** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/43#-:-KXXQNGl8XEvSRHxF0-o:bnfp4nl)*

**Comment by ilanpillemer** [comment]
*[src/main/liberty/config/server.xml, line 43 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/43#-KXXTJZCLGj6Yq_nyruu:-KXXTJZDMxVKpkwE8-dt:boauyw9) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cac6c9d04f4e4cfe0bf19d49b76b2b6bfc2b718/src/main/liberty/config/server.xml#L43)):*
> ```XML
>     
>     <include location="${env.TARGET}-config.xml" optional="true"/>
> ```

I assume this is a liberty specific file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/43)*

**Comment by ilanpillemer** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/43#-:-KXXTm0-UkzBe6TE-GO5:bnfp4nl)*

**Comment by ebullient** [comment]
Review status: 17 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/liberty/config/server.xml, line 43 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/43#-KXXTJZCLGj6Yq_nyruu:-KXXUaL2cRLLn3BhAkdf:bb77ucv) ([raw file](https://github.com/gameontext/gameon-room-java/blob/5cac6c9d04f4e4cfe0bf19d49b76b2b6bfc2b718/src/main/liberty/config/server.xml#L43)):*
<details><summary><i>Previously, ilanpillemer (Ilan Pillemer) wrote…</i></summary>
> I assume this is a liberty specific file?
</details>
Yep.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/43)*

**Comment by ebullient** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/43)*

**Comment by ebullient** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/43)*

**Comment by ebullient** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/43)*

**Pull request merged**
