### PR TITLE
Reorder walkthrough steps

### PR DESCRIPTION
**Pull request by katheris**
Reorder walkthrough steps to have:
Intro
General prereqs
Build local
Deploy (with link to Bluemix or Docker)
Register room
Find room in Game
Deploy to Bluemix
Deploy to Docker

---
This change is [Reviewable](https://reviewable.io/reviews/gameontext/gameon-room-java/25)

### CODE REVIEW

**Comment by ebullient** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[README.md, line 44 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ3v8ZbcfV64PDaZ5E:-KTQ3v8ZbcfV64PDaZ5F:byx28xo) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L44)):*
> ```Markdown
> or
> * [Deploy using Docker](#deploy-using-docker)
> ```

Coming out of either step, you should have cut/paste of the websocket URL you need for room registration

---

*[README.md, line 47 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ441kiA5HZaoQ1lDY:-KTQ441kiA5HZaoQ1lDZ:bstthpd) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L47)):*
> ```Markdown
> ## Registering your room
> 
> Microservices in production should support automatic scaling, with multiple instances of the room microservice running in parallel, with new instances starting or existing instances stopping at unpredictable times.  As a result of this, the room does not programmatically register itself by default. You can force it to do so by specifying the GAMEON_ID and GAMEON_SECRET environment variables.
> ```

We should remove the above. All signs of registration code in the room should be removed.

---

*[README.md, line 50 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ49gED8y2R36LcA35:-KTQ49gED8y2R36LcA36:bwk9ml7) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L50)):*
> ```Markdown
> 
> The preferred way to register a room is via the Edit Rooms dialog in Game On! (note you can also use the [command line regutil tool](https://github.com/gameontext/regutil) or the [interactive map](https://game-on.org/interactivemap)).
> ```

Take the above out.  "Use the Edit Rooms dialog in Game On! to register your room: "

---

*[README.md, line 59 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ4HRHg8eOC-GA4xen:-KTQ4HRHg8eOC-GA4xeo:bhj9l8m) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L59)):*
> ```Markdown
> 
> ## Access room on Game On!
> ```

Visit your room in the game (Hello, World!)

---

*[README.md, line 60 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ4R4oitkXePCZXsVQ:-KTQ4R4pyXvG9RG4vZpg:b-7jw37r) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L60)):*
> ```Markdown
> ## Access room on Game On!
> 
> Once the room is set up and it has registered with Game On!, it will be accessible on [Game On!](https://game-on.org/). It may take a moment for the room to appear.
> ```

...it will be accessible as a room in the game.

---

*[README.md, line 62 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ4ZQqy6OhLSjHVYlP:-KTQ4ZQqy6OhLSjHVYlQ:b-ig08h7) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L62)):*
> ```Markdown
> Once the room is set up and it has registered with Game On!, it will be accessible on [Game On!](https://game-on.org/). It may take a moment for the room to appear.
> 
> 1. Log in to [Game On!](https://game-on.org/) using the authentication method you used to create your user ID and shared secret for the registered room.
> ```

If you aren't in The First Room, use `/sos` to return there.

---

*[README.md, line 63 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ4qcJe9EZpVn24y0v:-KTQ4qcJe9EZpVn24y0w:bgm254y) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L63)):*
> ```Markdown
> 
> 1. Log in to [Game On!](https://game-on.org/) using the authentication method you used to create your user ID and shared secret for the registered room.
> 2. Use the Game On! command `/listmyrooms` from The First Room, to see your list of rooms. Once your room is registered, it will appear in that list.
> ```

"Your newly registered room should appear in the list"

---

*[README.md, line 64 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ4xOElOgBj4xOfWmN:-KTQ4xOElOgBj4xOfWmO:bbrleht) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L64)):*
> ```Markdown
> 1. Log in to [Game On!](https://game-on.org/) using the authentication method you used to create your user ID and shared secret for the registered room.
> 2. Use the Game On! command `/listmyrooms` from The First Room, to see your list of rooms. Once your room is registered, it will appear in that list.
> 3. To get to your room, navigate through the network or go directly there by using the `/teleport` command from The First Room.
> ```

Use the `/teleport` command to  go directly to your room to ensure it is running.

---

*[README.md, line 65 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ5Ae2wGnOMIYBz_E0:-KTQ5Ae2wGnOMIYBz_E1:bcj4rtu) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L65)):*
> ```Markdown
> 2. Use the Game On! command `/listmyrooms` from The First Room, to see your list of rooms. Once your room is registered, it will appear in that list.
> 3. To get to your room, navigate through the network or go directly there by using the `/teleport` command from The First Room.
> 4. Look at the Bluemix log console to see "A new connection has been made to the room"
> ```

Remove #4 here, or replace with, "[Look at the logs for your service](Link to section in advanced adventures dealing with finding logs in different environments) to see confirmation that a new connection has been made to the room"

---

*[README.md, line 71 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ5XUJp5ZT6zMymBUZ:-KTQ5XUJp5ZT6zMymBU_:b-p4i524) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L71)):*
> ```Markdown
> Suggested activities:
> * Make it more resilient -- add additional instances using the autoscaling add-on: https://console.ng.bluemix.net/catalog/services/auto-scaling
> * Consider how to allow chat messages to propagate between independent instances using a shared datastore or cache, or an event bus, or...
> ```

* Link to other advanced adventures in the book.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25)*

**Comment by ebullient** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25)*

**Comment by katheris** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[README.md, line 65 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ5Ae2wGnOMIYBz_E0:-KTT_5AjaKBdVlyGECCL:b-n6g4u6) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L65)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Remove #4 here, or replace with, "[Look at the logs for your service](Link to section in advanced adventures dealing with finding logs in different environments) to see confirmation that a new connection has been made to the room"
</details>
Will remove for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25)*

**Comment by katheris** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[README.md, line 47 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ441kiA5HZaoQ1lDY:-KTi40nrAqMqIw_sMNeW:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L47)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> We should remove the above. All signs of registration code in the room should be removed.
</details>
Done.

---

*[README.md, line 50 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ49gED8y2R36LcA35:-KTi42OcDO5p0hhSuDOu:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L50)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Take the above out.  "Use the Edit Rooms dialog in Game On! to register your room: "
</details>
Done.

---

*[README.md, line 59 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ4HRHg8eOC-GA4xen:-KTi44A6rjA11LmX8-Z-:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L59)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Visit your room in the game (Hello, World!)
</details>
Done.

---

*[README.md, line 60 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ4R4oitkXePCZXsVQ:-KTi467jjITZpqHvl1_d:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L60)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> ...it will be accessible as a room in the game.
</details>
Done.

---

*[README.md, line 62 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ4ZQqy6OhLSjHVYlP:-KTi47dbuyiavtcihvxn:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L62)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> If you aren't in The First Room, use `/sos` to return there.
</details>
Done.

---

*[README.md, line 63 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ4qcJe9EZpVn24y0v:-KTi48wrLCMF_44aq81W:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L63)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> "Your newly registered room should appear in the list"
</details>
Done.

---

*[README.md, line 64 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ4xOElOgBj4xOfWmN:-KTi4A5-I5c3Vo7BT-NZ:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L64)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Use the `/teleport` command to  go directly to your room to ensure it is running.
</details>
Done.

---

*[README.md, line 65 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ5Ae2wGnOMIYBz_E0:-KTi4Bl6_hGlT-UyBDiJ:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L65)):*
<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> Will remove for now.
</details>
Done.

---

*[README.md, line 71 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ5XUJp5ZT6zMymBUZ:-KTi4DFjwjMUlRlj58Lv:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L71)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> * Link to other advanced adventures in the book.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25)*

**Comment by katheris** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[README.md, line 44 at r1](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25#-KTQ3v8ZbcfV64PDaZ5E:-KTi4J7NluujtFibulyD:b-896fix) ([raw file](https://github.com/gameontext/gameon-room-java/blob/36288499097d3808fff6fdeb6eb2aca25447dfc6/README.md#L44)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Coming out of either step, you should have cut/paste of the websocket URL you need for room registration
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25)*

**Comment by ebullient** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-room-java/25)*

**Pull request merged**
